# Generated by Django 5.0 on 2023-12-20 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_scholarcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='schol_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.scholarcategory'),
        ),
    ]
