# Generated by Django 5.0 on 2023-12-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_schol_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='scholar_cat',
        ),
    ]
